### ISSUE TITLE
Forbering: Information om hvilken adresse, der fejler

### ISSUE THREAD

**Issue by MieWinstrup** [Septima/qgis-addresstoolsdk#6]
Problem identificeret af en bruger:

"Jeg har 848 adresser, som jeg kører igennem. En af adresserne giver en fejl, som får plugin’et til at fejle

Jeg har identificeret den adresse, det går galt med:
Vedbæk Strandvej  356,  2950 Vedbæk

Der findes ingen adresse, der har husnummer 356. Der skal et bogstav på. Prøver jeg at tilføje det, kan adressen godt geokodes uden fejl.

Et forbedringsforslag er selvfølgelig, at man får et hint om, hvilken adresse, pluginet fejler på … 

Fejlbesked:
QGIS version: 3.10.10-A Coruña

QGIS code revision: 8b051b9a43

Qt version: 5.11.2

GDAL version: 3.0.4

GEOS version: 3.8.1-CAPI-1.13.3

PROJ version: Rel. 6.3.2, May 1st, 2020

Processing algorithm…

Algorithm 'Geokod danske adresser med DAWA' starting…

Input parameters:

Traceback (most recent call last):
File "C:/Users/dbo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AddressToolsDK\addresstoolsdk_geocode_algorithm.py", line 223, in processAlgorithm
geocoded = geocoder.geocode(address)
File "C:/Users/dbo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\AddressToolsDK\addresstoolsdk_geocode_algorithm.py", line 93, in geocode
id = washed["resultater"][0]["aktueladresse"]["id"]
KeyError: 'aktueladresse'

Execution failed after 0.02 seconds

Loading resulting layers

Algorithm 'Geokod danske adresser med DAWA' finished

**Comment by MieWinstrup** [comment]
Rettet med version 0.2 beta / 0.3 (#14 ). Adresser som ikke kan geokodes vil ikke længere få pluginet til at stoppe, men vil blot få NULL værdier i de fire felter, der tilføjes.
